### PR TITLE
Add support for password hash attributes

### PR DESCRIPTION
**Pull request by katcsalameh**
This adds two attributes used to specify the how LDAP hashes passwords.
password_hash sets the type of hash that the LDAP server will use, while
password_crypt_salt_format sets the format of the salt.

### CODE REVIEW

**Comment by bodgit** [comment]
Cool, I'll commit this with a few tweaks. Notably I recently found these [additional password mechanisms](https://github.com/openldap/openldap/tree/master/contrib/slapd-modules/passwd) so I'll amend the regex to handle these.

**Comment by katcsalameh** [comment]
Thanks! I didn't know that OpenLDAP supported those additional mechanisms, good to know.

**Comment by bodgit** [comment]
They are however, a bit of a PITA to build. You basically need to have the full OpenLDAP source unpacked and `./configure`'d before you can build them. I was looking at how easy it would be to build some packages for these extra password modules and it looks like I'd have to duplicate most of the RPM spec.

**Comment by bodgit** [comment]
I managed to get SHA2 support built and tested so I've added some additional parameters that allow you to pull in additional packages for non-standard hashing schemes.

**Pull request merged**
